[general]
import = [
    "./themes/citylights.toml"
]

live_config_reload = true

[scrolling]
history = 100000

[terminal.shell]
program = "tmux"


[font]
size = 13

[mouse]
bindings = [
{ mouse = "Forward", mods = "None", action = "ScrollLineUp" },
{ mouse = "Back", mods = "None", action = "ScrollLineDown" },
]

[keyboard]
bindings = [
{ key = "c", mods = "Super", action = "Copy" },
{ key = "v", mods = "Super", action = "Paste" },
{ key = "q", mods = "Super", action = "Quit" },
{ key = "i", mods = "Super", action = "ToggleViMode" },
]
